### ISSUE TITLE
falu zé un probleme mek

### ISSUE THREAD

**Issue by Walkoud** [phormiz/SamuelPatcher#1]
c koi internet

**Comment by Seryu-Ub** [comment]
C'est une matrice universelle nous permettant de se rejoindre sur un réseau virtuel. Web que l'on peut traduire par "Toile" est un ensemble des données reliées par des liens hypertextes sur Internet.

**Comment by Walkoud** [comment]
dacor merci

**Comment by JeanOUINA** [comment]
slt boss fourre moi boss mrc boss
