### ISSUE TITLE
Patch

### ISSUE THREAD

**Issue by Zinovich** [phormiz/SamuelPatcher#2]
Je me suis fait blacklist à cause de cette version

**Comment by papycochon** [comment]
PTN  MAIS TUVASALAVERFMER

**Comment by papycochon** [comment]
aussi normalement ça peut pas blacklist

**Comment by JeanOUINA** [comment]
sex

**Comment by JeanOUINA** [comment]
sex

**Comment by r3ngan** [comment]
logique que tu te fasses blacklist, les trisomiques pensent qu'il n'y a pas de logs mais si, punchnox a quand même ton ip (mais ne fait rien avec et ne leak pas ton ip)  c'est juste un crack du punchnox détéctable de loin

**Comment by JeanOUINA** [comment]
le mec réponds 1 an après
