### ISSUE TITLE
des génies les devs

### ISSUE THREAD

**Issue by 002-sans** [phormiz/SamuelPatcher#3]
Salut, votre crack est périmé, déjà que les selfs ne marchent plus avec des embeds donc le github doit être supprimé et en plus que l'ip et l'id n'est pas du tout masqué ou même modifier et le risque de ban est 30x plus élever qu'avec le premium d'une autre personne sah, et le bonus est une version du self qui date donc pas dingue ce bonus inutile, et le pire c'est que vous mettez votre pub pour un crack aussi péter
![image](https://user-images.githubusercontent.com/99873347/156780871-c08c1f0f-cf9c-4453-a152-3f0e2220079f.png)

et mdrr un effort svp
![image](https://user-images.githubusercontent.com/99873347/156781804-0eb42db0-1588-465f-82a6-88d5b108dcdc.png)

**Comment by JeanOUINA** [comment]
jmen tape je garde le repo comme une archive

**Comment by ghost** [comment]
> Salut, votre crack est périmé, déjà que les selfs ne marchent plus avec des embeds donc le github doit être supprimé et en plus que l'ip et l'id n'est pas du tout masqué ou même modifier et le risque de ban est 30x plus élever qu'avec le premium d'une autre personne sah, et le bonus est une version du self qui date donc pas dingue ce bonus inutile, et le pire c'est que vous mettez votre pub pour un crack aussi péter ![image](https://user-images.githubusercontent.com/99873347/156780871-c08c1f0f-cf9c-4453-a152-3f0e2220079f.png)
> 
> et mdrr un effort svp ![image](https://user-images.githubusercontent.com/99873347/156781804-0eb42db0-1588-465f-82a6-88d5b108dcdc.png)

vous êtes aussi des génies toi et ksch à mettre un token grabber sur votre selfbot 
olalah "we fuck all" oh mon dieu

**Comment by 002-sans** [comment]
nous venons de tomber sur un paumé qui répond dans une issue fermé qui en plus date de mars, nous sommes déçu, surtout qu'il deobf l'index et l'update du TomoriProject (bzr la deobf ressemble à une deobf fait pas un tool) qui ne sont que les launchers et non le source code. Un peu de dignité stp. Ta bio est tout aussi inutile car https://github.com/WaifuWare/WFASelfbot et mettre des webhooks qui ne marche plus en prime sur un profile ça impose de la pitié pour toi du fait que c'est totalement inutile et con.

**Comment by 002-sans** [comment]
ton intervention ici est totalement inutile, tu aurais pu la fermer ça changeait rien

**Comment by JeanOUINA** [comment]
fermez la les bouffons on en a rien à foutre

**Comment by JeanOUINA** [comment]
je reçois des mails pour vos conneries fermez la
